### ISSUE TITLE
Enable logging when capturing

### ISSUE THREAD

**Issue by fepegar** [dzhoshkun/wherepy#33]
The lines I used to enable logging in https://github.com/dzhoshkun/wherepy/blob/master/wherepy/app/_collector.py#L6:
```
root = logging.getLogger()
root.setLevel(logging.DEBUG)
```

From https://stackoverflow.com/a/14058475/3956024

And I added the logging for each capture here: https://github.com/dzhoshkun/wherepy/blob/master/wherepy/app/_collector.py#L38

I'd PR, but you'll handle it more conveniently.

**Comment by dzhoshkun** [comment]
Thanks a lot, Fernando.
It's indeed important to have this real-time feedback.

**Comment by dzhoshkun** [comment]
Depends on #34 for testing.

**Comment by dzhoshkun** [comment]
* [ ] factor `display_status` and `display_header` et al. out to `wherepy.io`
* [ ] use those for the collector as well

**Comment by dzhoshkun** [comment]
* [ ] increase info field width
* [ ] reduce verbosity when reporting exceptions

**Comment by dzhoshkun** [comment]
* [ ] add a `--pretty` flag (shorter version?)

**Comment by dzhoshkun** [comment]
* [ ] https://github.com/dzhoshkun/wherepy/issues/32#issue-298740645
