### ISSUE TITLE
Info section of live capturing is truncated

### ISSUE THREAD

**Issue by fepegar** [dzhoshkun/wherepy#40]
The info message is sometimes truncated:
```
 (py2)  ~/tmp/  wherepy-collector-cli -p 100 -o test
|  Device  |       Signal      |   Error   |                Info                |
---------------------------------------------------------------------------------
  OFFLINE    [          ]  0 %       NA       Could not connect (Could not detec 
```

**Comment by dzhoshkun** [comment]
Thanks for the feedback, Fernando. The truncation is deliberate in this case. The live terminal UI relies on overwriting the status line using a carriage return (to avoid flooding the terminal with too much output). This might cause problems if the line gets too long and so spills over to the next line.

However I will:

* [ ] shorten the displayed messages instead. 

The message within the parentheses is the actual exception description, which sometimes contains newline characters, which could mess up the entire real-time display.

**Comment by dzhoshkun** [comment]
@fepegar The info messages have been shortened, and the status line format handling improved.
